services:
  db:
    restart: always
    image: postgres:12.3
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "simple_jwt"
    expose:
      - "5432"
    volumes:
      - "simple_jwt:/var/lib/postgresql/data"
    command: >-
        --jit=false
    ports:
      - "5432:5432"

volumes:
  simple_jwt:
